### ISSUE TITLE
Tracking issue: Tide action history page.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#10646]
Tracking issue for follow up steps for #10530 

Today the `/tide-history` endpoint is not linked to or mentioned anywhere. Once the page has been validated in Prod I'll:
- [x] link to it from Decks navigation menu
- [x] make the Tide dashboard and PR status page link to the appropriate filters
- [x] add an announcement to [ANNOUNCEMENTS.md](https://github.com/kubernetes/test-infra/blob/master/prow/ANNOUNCEMENTS.md)
- [x] update the Tide docs to mention the new page
- [x] send an email to k-dev mentioning the new page and reminding contributors about the PR status page. (Maybe also link to this doc too: https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/pr-authors.md)

Additional follow up:
- [x] Backup and restore history data from GCS so that history is persistent between restarts of the Tide pod.

cc @stevekuznetsov @Katharine 
/assign
/kind feature

**Comment by spiffxp** [comment]
So we have https://prow.k8s.io/tide-history, I'm curious what if anything re "validated in prod" before we can move on the rest

**Comment by cjwagner** [comment]
I want to enable and validate the GCS persistence, and make the page discoverable by adding links. Once that is done we can publicize it, but I think we need to have persistence and a link from Deck's side bar before we suggest that anyone uses or relies on the page.

**Comment by cjwagner** [comment]
This is done.
/close
