### ISSUE TITLE
Submit Queue Batching

### ISSUE THREAD

**Issue by rmmh** [kubernetes/test-infra#1092]
Testing one PR at a time is slowing down Kubernetes development a lot.

Design doc [here](https://docs.google.com/document/d/1WYv4Ee4VFnCVwQHIYb3ashZ4ZQuOjMrvG0vdPCC_Lts/view).

TODO:
- [x] Make Splicer program to find batch opportunities and push to Prow. #1063
- [x] Make bootstrap.py understand how to checkout and merge multiple PRs for batch testing. #1090
- [x] Make Splicer start (either create jobs directly, or tell hook to do it) and monitor (with deck) batch jobs on Prow. #1168
- [x] Make Submit Queue use passing batch test results on Prow to merge faster (in parallel with normal serial testing). kubernetes/contrib#2078
- [x] Make Gubernator display batch results properly. #1241

**Comment by fejta** [comment]
Woo! Close?
