### ISSUE TITLE
Tracking Issue: Prow HEAD and stability

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#11679]
Following #11430 we have a couple items to clean up. We need to re-revert the changes that were reverted and make sure that the system remains stable. The working theory was that the reverted changes caused excessive CPU and memory usage, so we need to add instrumentation to track that and determine if it is true. 

The best deployment to do testing on is `deck` as it's replicated and degraded performance does not affect the stability of the system. Changes to `deck` liveness/readiness probes would be nice before this process as they will make rollouts smoother.

The following steps are suggested:

 - [x] add liveness/readiness endpoints to `deck`: #11659 | @stevekuznetsov 
 - [x] add `pprof` debug endpoints to `deck`: https://github.com/kubernetes/test-infra/pull/11682 | @stevekuznetsov 
 - [x] ensure new endpoints actually work in `deck`: https://github.com/kubernetes/test-infra/pull/11692 | @stevekuznetsov 
 - [x] deploy the version of `deck` with new endpoints: https://github.com/kubernetes/test-infra/pull/11699 | @fejta 
 - [x] add liveness/readiness probes to `deck`: https://github.com/kubernetes/test-infra/pull/11680 | @stevekuznetsov  
 - [x] let `deck` soak at this state and get debug traces, measure CPU and memory use: @cjwagner 
 - [x] update client loading code: https://github.com/kubernetes/test-infra/pull/11667 | @fejta 
 - [x] re-revert `deck` client changes: https://github.com/kubernetes/test-infra/pull/11733 | @fejta 
 - [x] deploy the version of `deck` with the re-revert: https://github.com/kubernetes/test-infra/pull/11735 | @fejta 
 - [x] let `deck` soak at this state and get debug traces, measure CPU and memory use: @cjwagner 

Once this has succeeded, we can follow up with:
 - [x] limit concurrency in `tide`: https://github.com/kubernetes/test-infra/pull/11675 | @fejta 
 - [x] make `tide` robust to partial results: https://github.com/kubernetes/test-infra/pull/11695 | @fejta 
 - [x] make `tide` queries deterministic: https://github.com/kubernetes/test-infra/pull/11712 | @fejta 
 - [x] deploy `tide` with GitHub fixes: https://github.com/kubernetes/test-infra/pull/11713 | @fejta 
 - [ ] re-revert `plank` client changes: TODO | @fejta  
 - [ ] deploy the version of `plank` with the re-revert: TODO | (on-call?)
 - [x] re-revert `tide` client changes: #11759 | @fejta  
 - [x] deploy the version of `tide` with the re-revet https://github.com/kubernetes/test-infra/pull/11752 | @fejta
 - [x] eliminate tide status brownout after restart #11742 | @fejta
 - [x] deploy the version of `tide` with these changes https://github.com/kubernetes/test-infra/pull/11752 | @fejta

/cc @cjwagner @fejta @BenTheElder @krzyzacy @Katharine 
/area prow
/area prow/deck
/area prow/plank
/area prow/tide

**Comment by fejta** [comment]
This needs https://github.com/kubernetes/test-infra/pull/11667 as well

**Comment by stevekuznetsov** [comment]
If you merge #11667 then you will need to own the re-reverts as they will be more involved

**Comment by stevekuznetsov** [comment]
We're ready to gather CPU/mem data from `deck`

**Comment by stevekuznetsov** [comment]
Deck client re-revert went smoothly

**Comment by stevekuznetsov** [comment]
Only `plank` re-reverts and re-deployment is left for this tracking issue.

**Comment by stevekuznetsov** [comment]
@clarketm 
<3 :tada: 
/close
