### ISSUE TITLE
[Tracking] Consolidate and automate creation of sig-release owned testgrid dashboards 

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/test-infra#11977]
(Following up from the [last sig-release catchup](https://www.youtube.com/watch?v=u9gK3zWDO9M) ([notes](https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA/edit#bookmark=id.r3c7r9efjr3)))

Context: At the end of the 1.13 release, we [rearranged](https://github.com/kubernetes/test-infra/pull/10914) sig-release owned dashboards into blocking and informing, based on criteria discussed in https://github.com/kubernetes/sig-release/issues/347.

**What should be cleaned up or changed**:
- [x] Consolidate `master-` dashboards in `master-blocking` and `master-informing`, by moving `master-upgrade` jobs into one of them (~https://github.com/kubernetes/test-infra/pull/12441~ https://github.com/kubernetes/test-infra/pull/12511)
- [ ] Shape 1.14-blocking to contain exact equivalents of `master-blocking`, by moving all other 1.14- jobs into 1.14-informing  _(add issue/PR here)_
- [ ] Resolve the `1.14-informing` - `master-informing` diff, by 
  - auditing the diff
  - for jobs that exist in one but not the other dashboard, deleting or porting over accordingly
 _(add issue/PR here)_
- [ ] Create tooling to automate creation of `<non-master>-` dashboards and their contents (e.g. prow jobs), using `master-` dashboards as input  (#12443 and followups)

**Related/Complementary, but out of scope for this work:**
* Upgrade tests should move to use a community supported way of upgrading clusters

cc @alejandrox1 @spiffxp @claurence @neolit123 @tpepper @calebamiles @jberkus 
/sig release

**Comment by mariantalla** [comment]
Re: consolidating master-dashboards, we spoke about moving them to -informing rather than -blocking, because they use `/cluster` (=non-community-supporting) scripts to upgrade clusters. For 1.14, CI signal treated them as equally blocking as master-blocking. They're also currently the only way we have to get signal on how stable upgrades are, so I feel there is a good argument for them to move into blocking too. 

@alejandrox1 @claurence thoughts?

**Comment by spiffxp** [comment]
/assign @spiffxp @mariantalla 
I would like to help push this with maria (whom I've assigned because she's started pushing this in #12441)

/assign @alejandrox1 
CI Signal for v1.15

FYI @claurence as 1.15 release lead

FYI @Katharine given you are trying to help simply forking of the jobs that end up on these dashboards (ref: https://github.com/kubernetes/test-infra/pull/12443)

**Comment by spiffxp** [comment]
>Create tooling to automate creation of <non-master>- dashboards and their contents (e.g. prow jobs), using master- dashboards as input (add issue/PR here)

/assign @Katharine 
Now that I'm reading a little more closely, this is what https://github.com/kubernetes/test-infra/pull/12443 is for, so assigning to make sure we agree this is done

**Comment by spiffxp** [comment]
I am, FWIW, trying to link anything related to "clean up release dashboards" or "clean up release jobs" or "make these things more consistent" etc, because this seems like the most relevant umbrella

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/issues/11977 is adding -informing dashboards for all branches

**Comment by spiffxp** [comment]
We are now in an intermediary state I would like to get out of:
- release-x.y-blocking
- release-x.y-informing
- release-x.y-all

I want us to get rid of -all

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/issues/13883

**Comment by justaugustus** [comment]
Hopping on this since I've done recent-ish work to spruce these boards up:
- Create `sig-release-job-config-errors` dashboard: https://github.com/kubernetes/test-infra/pull/15023
- Signal potentially misconfigured jobs and delete sig-release-x.y-all dashboards: https://github.com/kubernetes/test-infra/pull/15039
- sig-release: Rearrange dash configs and prune some jobs from sig-release-job-config-errors: https://github.com/kubernetes/test-infra/pull/15068

What remains for us to do to close this out?

/assign
/remove-lifecycle stale
/lifecycle frozen

**Comment by spiffxp** [comment]
/close
I can't think of anything off the top of my head so I think we should close. If there's something specific that comes up, use followup issues.
