### ISSUE TITLE
Tracking issue: Stabl(ish) Prow images

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#14582]
This is a tracking issue for the migration plan outlined here: https://docs.google.com/document/d/1kBo24FbmeF-h1dk78wi9vnKXU-QkCXI9Ul1XEW9qVls/edit#heading=h.23gq093vwv2w

Prerequisites:
- [x] Set up gcr.io/k8s-prow-edge repo
- [ ] Add cip-manifest.yaml and post-submit cip job.
This won’t do anything until we start updating the file with the stable-image-suggester (or manually PR changes to the manifest for testing).
- [ ] Get stable-image-suggester merged so that it is ready to use.
- [ ] Make post-test-infra-push-prow push images to gcr.io/k8s-prow-edge in addition to gcr.io/k8s-prow https://github.com/kubernetes/test-infra/pull/14580

User impacting changes:
- [ ] Switch edge prow instance (currently prow.k8s.io) to use gcr.io/k8s-prow-edge images
Simultaneously update autobumper to expect gcr.io/k8s-prow-edge instead of gcr.io/k8s-prow.
- [ ] Stop post-test-infra-push-prow from pushing to both repos and only push to gcr.io/k8s-prow-edge.

One day later:
- [ ] Merge stable-image-suggester periodic job the next day. (If we don’t wait a day the suggester won’t find any gcr.io/k8s-prow-edge images that were used at yesterday’s commit.)

cc @stevekuznetsov @fejta @BenTheElder
