### ISSUE TITLE
Migrate away from deprecated `--build-cluster` flag and format.

### ISSUE THREAD

**Issue by clarketm** [kubernetes/test-infra#14810]
**What should be cleaned up or changed**:

Migrate away from and deprecate `--build-cluster` flag and format.
- [x] Migrate K8s Prow deployments to use `--kubeconfig` (#16906)
- [x] Deprecation and removal of `mkbuild-cluster`
  - [x] Create an [announcement](https://github.com/kubernetes/test-infra/blob/master/prow/ANNOUNCEMENTS.md) and set removal date, #15285.
  - [x] Replace `mkbuild-cluster` references in [`getting_started_deploy.md`](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md) with the equivalent `gencred` command(s), #15285.  
  - [x] Remove `mkbuild-cluster` source code ([ref](https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml)), **to be completed May 2020**, #15287.
  - [x] Remove `mkbuild-cluster` label ([ref](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/mkbuild-cluster)), **to be completed May 2020**, #15287.

/assign

**Comment by BenTheElder** [comment]
> Migrate K8s Prow deployments to use --kubeconfig

Doesn't seem like contributors can handle this? Also you've already assigned yourself...?

**Comment by clarketm** [comment]
/kind oncall-hotlist

The only thing left is on-call **process**: create a `kubeconfig` file, save it in a secret, and define it (using `--kubeconfig`) on the k8s resources that require it (e.g. `plank`, `sinker`, `deck`).

**Comment by fejta** [comment]
Would be great to make some progress on here, happy to help out during my oncall shift.

**Comment by fejta** [comment]
/assign @fejta @clarketm 

Do we have a tool to create the kubeconfig file? (convert the existing one?)

**Comment by clarketm** [comment]
> Do we have a tool to create the kubeconfig file? (convert the existing one?)

Yes, that is [`gencred`](https://github.com/kubernetes/test-infra/tree/master/gencred). Its usage has been added to the Prow getting started guide https://github.com/kubernetes/test-infra/pull/15285.

**Comment by fejta** [comment]
/unassign @clarketm 
I'll give it a go then, thanks!

**Comment by fejta** [comment]
Still pending

**Comment by clarketm** [comment]
>  Migrate K8s Prow deployments to use `--kubeconfig`

This should only be a [single command followed by a PR to update object config yaml](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/cm2kc/README.md#examples). Can someone with **k8s-prow** cluster access give this a try before **May 2020**?

---

**Note:** The `build-cluster` format is planned for removal in **May 2020** ([ref](https://github.com/kubernetes/test-infra/blob/master/prow/ANNOUNCEMENTS.md)).
