### ISSUE TITLE
Delete unused secrets in service cluster default namespace

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#16464]
ref #15806 

/assign

- [x] `ci-service-account`, `kubekins@kubernetes-jenkins.iam.gserviceaccount.com`, `2152c16d13db` (super old)
- [x] `tide-history-service-account`, `tide-history@k8s-prow.iam.gserviceaccount.com` (migrating to workload identity) #16465
- [x] `service-account`, `pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com` (migrating to workload identity) #16466 #16475
- [ ] `triage-service-account` #16462

**Comment by fejta** [comment]
```console
fejta@fejta3:~/src/gh/test-infra$ gsutil ls -l gs://k8s-prow
  12990770  2020-02-25T18:40:54Z  gs://k8s-prow/tide-history.json
      1101  2020-02-25T18:18:09Z  gs://k8s-prow/tide-status-checkpoint.yaml
TOTAL: 2 objects, 12991871 bytes (12.39 MiB)
fejta@fejta3:~/src/gh/test-infra$ kubectl --context=prow delete secrets tide-history-service-account
secret "tide-history-service-account" deleted
fejta@fejta3:~/src/gh/test-infra$ date
Tue 25 Feb 2020 10:42:02 AM PST
```

**Comment by fejta** [comment]
```console
fejta@fejta3:~/src/gh/test-infra$ grep -R "secretName: service-account" prow/cluster 
prow/cluster/grandmatriarch.yaml:          secretName: service-account
prow/cluster/boskos-janitor.yaml:          secretName: service-account
prow/cluster/boskos-janitor.yaml:          secretName: service-account
fejta@fejta3:~/src/gh/test-infra$ kubectl --context=prow get deployments -o yaml | grep service-account
fejta@fejta3:~/src/gh/test-infra$ kubectl --context=prow delete secrets service-account && date
secret "service-account" deleted
Tue 25 Feb 2020 10:53:50 AM PST
```
