### ISSUE TITLE
[Tracker] Add CRI-O based e2e tests

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/test-infra#16589]
This is the tracking issue for adding CRI-O based Kubernetes end-to-end tests into test-infra.

As far as I can see, we need the following:

- [ ] A custom image based on a regular distribution, like Fedora
    See: https://github.com/kubernetes/test-infra/tree/master/jobs/e2e_node/containerd 
- [ ] Job definitions, like the containerd ones
    See: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/containerd.yaml
- [ ] A way to promote the tests into Kubernetes Pull Requests
    See: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml

#### Constraints
- For the initial implementation I'd like to focus on one common distribution (Fedora for now)

#### Open Questions
- What else do we need?
- How can I test the custom image?

/cc @haircommander @mrunalp 
/cc @kubernetes/sig-node

**Comment by saschagrunert** [comment]
Ref https://github.com/kubernetes/test-infra/pull/17014
