### ISSUE TITLE
kind is missing release-1.18 jobs

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#16700]
**What should be cleaned up or changed**:
- [x] the kind release-blocking job for master currently runs conformance tests only and relies on the kubekins image, it should be brought in line with the merge-blocking presubmit job which runs more tests and uses krte (#16704)
- [x] a variant of krte should be built for release-1.18 (#16701)
- [x] ensure a k/k presubmit for release-1.18 and ci jobs for release-1.18 exist (#16729)
- [x] setup config-forker/config-rotator annotations for the kind jobs so they won't be missed the next time jobs are forked/rotated (#16740)

**Provide any links for context**:
- ref: https://github.com/kubernetes/test-infra/issues/9363

/assign
