### ISSUE TITLE
[Umbrella] Approval-process roll-out

### ISSUE THREAD

**Issue by apelisse** [kubernetes/test-infra#1678]
We've noticed a bunch of bugs and/or requirement as we've been rolling out the approval-process. Let's use this issue as an umbrella to open all related issues and keep track of progress (and make sure we fix bugs only once):

List of issues:
- [x] #1639 Deterministically Choose Approvers 
- [x] #1672 Mungebot: Only one command is parsed from comment
- [x] #1676 Mungebot: It takes two cycles to get approved label detected
- [x] #1680 Mungebot: Update to APPROVALNOTIFIER comments are hard to notice
- [ ] #1687 Approvers: make the approvers assignees for the PR
- [x]  #1701 Confusion between OWNER_ALIAS + APPROVERNOTIFIER
- [x] #1727 Approvers: Machine-Readable Assignments
- [x] #1673 Mungebot: Allow commands anywhere in the comment
- [x] #1743 mungegithub: Make approval label sticky
- [x] #1744 mungegithub: Proposal: /lgtm also approves
- [x] #1750 mungegithub: Link approver to approval comment in notification
- [x] #1751 mungegithub: proposal: PRs from approvers automatically self-approve their packages
- [x] #1767 mungebot/Approval: Improve code design and add quality unit-tests  (refactor)
- [x] #1769 mungebot/Approval: if existing assignees can fully approve PR, don't reassign
- [x] #1770 mungebot/Approval: fix randomization of approvers (when choosing suggestions)
- [ ] #1782 mungebot/Approval: ownerless files and not recursive ownership
- [ ] #1790 approved label is out of sync with approval comment/status 
- [ ] #1828 mungebot/Approval: cherry pick PRs shouldn't need approval
- [ ] #1965 Mungebot: Approval notif refreshes constantly if commit date is in the future 
- [x] #1967 [mungegithub/approvers] Misleading Approvers
- [x] #2071 Approval: Bot reads `/lgtm cancel` as an approval 
- [x] #2076 mungebot/approval: cc only applicable approvers
- [x] #2123 Make OWNERS files case-insensitive
- [x] #2215 Don't make a comment if the PR is already approved.

**Comment by apelisse** [comment]
What is the consequence of that?
