### ISSUE TITLE
Prow issue: redesign cmd/line, cmd/tot, cmd/deck, ..., oh dear.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#2054]
**Overview:**

We will replace `cmd/line` with a custom controller that stores state in k8s ThirdPartyResources (TPRs).

**Currently:**

1. Something decides we to run a test. This can be `cmd/hook` if a PR was just updated, `cmd/splice` if it's time to start a new batch, `cmd/horologium` if a periodic job is due, and in the future we might support user triggering. All of these sources call a function in `prow/line` that is simply a thin wrapper around starting a k8s Job with the appropriate flags.
1. The k8s job starts up. It discovers its name through the DownwardAPI. It picks a build number using `cmd/tot`, and reports its status using `cmd/crier`. It polls Jenkins or k8s through their REST APIs. We run about 200 `line` jobs concurrently at peak times.
1. `cmd/deck` polls the k8s API for job results. Job state is stored in the actual k8s Job object on etcd.

**Problems with this approach:**

1. The code in `line/` and `cmd/line` is super complex. It's difficult to test because the interaction between "a job was triggered" and "Jenkins/k8s begin testing" involves the k8s API server.
1. We hit the Jenkins and k8s API servers hard, because every line job is polling.
1. We waste cluster resources running 200 copies of the same binary. Most of the time they're idle, but it's still not trivial.

**Solution:**

Use a ThirdPartyResource and a custom controller.

* It stores state in one or many k8s TPRs, similar to how we now store it in Jobs. However, we can define our own spec for the TPR, so rather than setting random flags in a k8s job spec, we can explicitly set field sin the TPR. This makes testing much easier.
* Start jobs by creating such a resource.
* The controller has a sync loop that stops/starts jobs on k8s/Jenkins and updates their statuses.
* It can query the k8s pod list once per sync loop rather than once per sync loop per job.

**Steps:**

- [x] Make `cmd/sinker` delete both jobs and TPRs. #2218
- [x] Write a controller that looks at TPRs and triggers `line` jobs in the current way. #2243 #2395
- [x] Switch `cmd/horologium` to trigger in this way as a sanity check. #2391
- [x] Make `cmd/deck` read jobs and TPRs both. #2420
- [x] Move `cmd/line`'s behavior into the controller. #2429 #2451 #2466 
- [x] Delete `cmd/line` and `line` packages, point things that start jobs at `plank` instead. #2466
- [x] Document `plank` usage. #2473

**Comment by rmmh** [comment]
What happens if a node goes offline while running jobs?

**Comment by spxtr** [comment]
Which node? If it's the node with the controller on it then k8s will start a new pod on a new node, and since it stores all memory in TPRs on etcd, we won't even notice.

If it's a node running a build pod then the controller may want to restart it. Currently, `cmd/line` does not restart in this case, and it's never happened before.

**Comment by kargakis** [comment]
> We hit the Jenkins and k8s API servers hard, because every line job is polling.

How is this different with ProwJobs? You are still going to hit the k8s API server right? Or is there a plan to have ProwJobs work with their own API server?

**Comment by spxtr** [comment]
With ProwJobs there will be a single controller polling the k8s api server and Jenkins, rather than 200 `cmd/line` programs all polling. This has caused us problems in the past, when Jenkins would fall over trying to serve our load ("error in queue" showed up on PRs for a day or two due to this).

**Comment by spxtr** [comment]
Done.

**Comment by fejta** [comment]
k8s-ci-robot added the label kind/interesting

**Comment by mtanski** [comment]
We've build a system around bare Pods to encapsulate our bath job system. The current Job system is opinionated to the point of not being useful. Continuously running the same failing job (or group of failing jobs) and blocking resources for other ones to run is not great default choice.
