### ISSUE TITLE
Checklist for implementing the e2e flakiness SLA

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/test-infra#2103]
I have proposed an SLA for flakiness here:
https://github.com/kubernetes/community/pull/422

This issue tracks what is needed to implement it.

- [x] Document the flakiness SLA for the community
- [x] Implement a collector that scraps github and finds PRs with flakes
- [x] Store those metrics into a logging system somewhere
- [ ] Create an SLA dashboard on mungegithub

**Comment by spxtr** [comment]
cc @apelisse for the collector and metric storage.

**Comment by fejta** [comment]
On thing left is the dashboard, which is something that we will work on soon:
/assign @cjwagner

**Comment by spiffxp** [comment]
/close
We now have http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1 per #3344
