### ISSUE TITLE
Documentation Revamp

### ISSUE THREAD

**Issue by listx** [kubernetes/test-infra#24821]
**What should be cleaned up or changed**:

Migrate existing *.md files into a centralized location. It would also help greatly if we can do what the [KIND team has done](https://kind.sigs.k8s.io/docs/user/quick-start/) and go with static site generation to make the docs more user-friendly (and not default to the default GitHub markdown file view).

As for the type of docs, this effort will focus on improving docs for Prow users, not developers. Later on we can also improve docs for developers but this is not a priority for now.

Ultimately, the goal is to make the docs easier to maintain. With that in mind we should add a freshness checker that can alert doc owners/maintainers to periodically check them for accuracy. If a docs freshness checker already exists in the K8s community, we can try reusing that but otherwise we'll have to create one from scratch.

**Provide any links for context**:

[Design doc](https://docs.google.com/document/d/17_gyhQipmK_roYqUtwx-hTwi1tn2sd0aG6vdkBn6fKM/edit?usp=sharing) (shared with kubernetes-dev@googlegroups.com and dev@kubernetes.io).

Looping in Kubernetes SIG Docs to get some feedback about the idea of a periodic docs freshness checker.
@kubernetes/sig-docs-en-reviews 

# TODO items

## Get a new prow docs repo created!

- [x] Resolve https://github.com/kubernetes/org/issues/3228

## Get the Netlify preview up and running

- [x] Create dedicated Prow documentation-hosting GitHub repo
- [x] add `netlify.toml` to this same repo
- [x] Merge https://github.com/kubernetes/test-infra/pull/25042 (obsolete, as this is in the old k/t-i repo, not the dedicated (to be created!) Prow repo)
- [x] Resolve https://github.com/kubernetes/org/issues/3177
- [x] Fix build issues with the docs site (see https://github.com/kubernetes-sigs/prow/pull/3)

## Get a bare-bones site up (actual content to be fleshed out later)
- [x] Merge https://github.com/kubernetes-sigs/prow/pull/1

## Get docs.prow.k8s.io DNS redirect set up (to point to the Netlify site)
- [x] Resolve https://github.com/kubernetes/k8s.io/issues/3315

**Comment by stevekuznetsov** [comment]
See also the OpenShift CI [docs website](https://docs.ci.openshift.org/docs/) which a) has a lot of pertinent information and b) seems to have followed most of the same decisions you came to in the design doc. Well done! The OpenShift site tries to link to the markdown wherever possible, and _isn't_ trying to document generic Prow things as much as it can, but of note pages like [this](https://docs.ci.openshift.org/docs/how-tos/notification/) are good examples of developer-focused "how do I achieve <thing>" sort of things I think a user-facing docs site for Prow in general should do.

One more note - there's probably some utility to having some clear delineation between Prow documents writ large and _prow.k8s.io_ documentation - of course Prow-deployment-specific choices bubble up, but keeping the two semi-separate will at least allow other deployments to link back to some central set of documents that apply everywhere.

**Comment by listx** [comment]
Hi Steve, sorry I took so long to circle back to your comments. Thank you for reading the design doc and leaving feedback (I've left responses to each one, please take another look).

The OpenShift CI docs website looks almost identical to the https://kubernetes.io/docs/home/ site, which is what I kept in mind (apart from KIND's docs site). I will try to lean on these existing examples as much as possible to avoid reinventing the wheel.

> there's probably some utility to having some clear delineation between Prow documents writ large and prow.k8s.io documentation

The more we tailor the docs to specific audiences, the better.

**Comment by listx** [comment]
https://docs.prow.k8s.io is now live!

All that remains is to (1) migrate existing docs over to this site and (2) add prow jobs for checking for broken links, freshness, etc (as discussed in the design doc linked in the first comment). I will create new issues for these efforts in the new repo and cross-reference this issue. When those issues are created (and tracked) there, we can close this.

**Comment by listx** [comment]
The issues have been created in the new repo. Closing this one.
