### ISSUE TITLE
[Umbrella Issue] Update the mentions of testgrid dashboard URL from k8s-testgrid.appspot.com to testgrid.k8s.io

### ISSUE THREAD

**Issue by letmerecall** [kubernetes/test-infra#30370]
**What happened**:

Somewhere down the line, the domain name of the testgrid dashboard was updated from `k8s-testgrid.appspot.com` to `testgrid.k8s.io`.  After the update old domain now throws a 'page not found error'. There're numerous links to the old testgrid dashboard's domain which across many projects now stands broken.

Related slack conversation: https://kubernetes.slack.com/archives/C09QZ4DQB/p1689609631562029?thread_ts=1689589511.968429&cid=C09QZ4DQB

<img width="892" alt="Screenshot 2023-08-14 at 1 14 08 PM" src="https://github.com/kubernetes/test-infra/assets/19938474/a8b8da69-b241-4f77-9faf-c8fed107fefd">

**What you expected to happen**:
This issue aims to track the update of the testgrid dashboard's URL across different projects. Once updated we expect to have no broken links to the testgrid dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
Visit: https://k8s-testgrid.appspot.com

**Projects:**

Repos/projects where the link to the old testgrid dashboard domain (`k8s-testgrid.appspot.com`) was found by doing a [cs.k8s.io search](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=).

- [x] [kubernetes/enhancements](https://github.com/kubernetes/enhancements) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes/enhancements) | https://github.com/kubernetes/enhancements/pull/4154
- [x] [kubernetes/sig-release](https://github.com/kubernetes/sig-release) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes/sig-release) | https://github.com/kubernetes/sig-release/pull/2305
- [x] [kubernetes/community](https://github.com/kubernetes/community) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes/community) | https://github.com/kubernetes/community/pull/7472
- [x] [kubernetes/test-infra](https://github.com/kubernetes/test-infra) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra) | https://github.com/kubernetes/test-infra/pull/30371
- [x] [kubernetes/website](https://github.com/kubernetes/website) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes/website) | https://github.com/kubernetes/website/pull/42538  (Maintaining old blogs are discouraged)
- [x] [kubernetes-sigs/lwkd](https://github.com/kubernetes-sigs/lwkd) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-sigs/lwkd) | https://github.com/kubernetes-sigs/lwkd/pull/216
- [x] [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes/kubeadm) | https://github.com/kubernetes/kubeadm/pull/2918
- [x] [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes/kubernetes) | https://github.com/kubernetes/kubernetes/pull/119934
- [x] [kubernetes/release](https://github.com/kubernetes/release) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes/release) | https://github.com/kubernetes/release/pull/3211
- [x] [kubernetes-csi/csi-driver-nfs](https://github.com/kubernetes-csi/csi-driver-nfs) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/csi-driver-nfs) | https://github.com/kubernetes-csi/csi-driver-nfs/pull/500
- [x] [kubernetes-csi/csi-driver-smb](https://github.com/kubernetes-csi/csi-driver-smb) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/csi-driver-smb) | https://github.com/kubernetes-csi/csi-driver-smb/pull/654
- [x] [kubernetes-csi/csi-test](https://github.com/kubernetes-csi/csi-test) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/csi-test) | https://github.com/kubernetes-csi/csi-test/pull/477
- [x] [kubernetes/autoscaler](https://github.com/kubernetes/autoscaler) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes/autoscaler) | https://github.com/kubernetes/autoscaler/pull/6036
- [x] [kubernetes/ingress-gce](https://github.com/kubernetes/ingress-gce) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes/ingress-gce) | https://github.com/kubernetes/ingress-gce/pull/2237
- [x] [kubernetes-csi/csi-driver-host-path](https://github.com/kubernetes-csi/csi-driver-host-path) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/csi-driver-host-path) |  (subtree)
- [x] [kubernetes-csi/csi-driver-iscsi](https://github.com/kubernetes-csi/csi-driver-iscsi) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/csi-driver-iscsi) | (subtree)
- [x] [kubernetes-csi/csi-driver-nvmf](https://github.com/kubernetes-csi/csi-driver-nvmf) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/csi-driver-nvmf) | (subtree)
- [x] [kubernetes-csi/csi-lib-utils](https://github.com/kubernetes-csi/csi-lib-utils) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/csi-lib-utils) | (subtree)
- [x] [kubernetes-csi/csi-proxy](https://github.com/kubernetes-csi/csi-proxy) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/csi-proxy) | (subtree)
- [x] [kubernetes-csi/csi-release-tools](https://github.com/kubernetes-csi/csi-release-tools) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/csi-release-tools) | https://github.com/kubernetes-csi/csi-release-tools/pull/234
- [x] [kubernetes-csi/external-attacher](https://github.com/kubernetes-csi/external-attacher) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/external-attacher) |
- [x] [kubernetes-csi/external-health-monitor](https://github.com/kubernetes-csi/external-health-monitor) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/external-health-monitor) | (subtree)
- [x] [kubernetes-csi/external-provisioner](https://github.com/kubernetes-csi/external-provisioner) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/external-provisioner) |
- [x] [kubernetes-csi/external-resizer](https://github.com/kubernetes-csi/external-resizer) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/external-resizer) |
- [x] [kubernetes-csi/external-snapshotter](https://github.com/kubernetes-csi/external-snapshotter) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/external-snapshotter) |
- [x] [kubernetes-csi/lib-volume-populator](https://github.com/kubernetes-csi/lib-volume-populator) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/lib-volume-populator) |
- [x] [kubernetes-csi/livenessprobe](https://github.com/kubernetes-csi/livenessprobe) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/livenessprobe) |
- [x] [kubernetes-csi/node-driver-registrar](https://github.com/kubernetes-csi/node-driver-registrar) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/node-driver-registrar) |
- [x] [kubernetes-csi/volume-data-source-validator](https://github.com/kubernetes-csi/volume-data-source-validator) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-csi/volume-data-source-validator) | (subtree)
- [x] [kubernetes-sigs/gluster-block-external-provisioner](https://github.com/kubernetes-sigs/gluster-block-external-provisioner) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-sigs/gluster-block-external-provisioner) | (subtree)
- [x] [kubernetes-sigs/gluster-file-external-provisioner](https://github.com/kubernetes-sigs/gluster-file-external-provisioner) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-sigs/gluster-file-external-provisioner) | (sidecar)
- [x] [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner](https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-sigs/nfs-ganesha-server-and-external-provisioner) |  (subtree)
- [x] [kubernetes-sigs/nfs-subdir-external-provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-sigs/nfs-subdir-external-provisioner) | https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/302 (subtree)
- [x] [kubernetes/dns](https://github.com/kubernetes/dns) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes/dns) | https://github.com/kubernetes/dns/pull/595
- [x] [kubernetes/kubectl](https://github.com/kubernetes/kubectl) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes/kubectl) | https://github.com/kubernetes/kubectl/pull/1476 (subtree)
- [x] [kubernetes/node-problem-detector](https://github.com/kubernetes/node-problem-detector) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes/node-problem-detector) | https://github.com/kubernetes/node-problem-detector/pull/794
- [x] [kubernetes/perf-tests](https://github.com/kubernetes/perf-tests) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes/perf-tests) | https://github.com/kubernetes/perf-tests/pull/2307
- [x] [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) | https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1407
- [x] [kubernetes-sigs/hierarchical-namespaces](https://github.com/kubernetes-sigs/hierarchical-namespaces) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes-sigs/hierarchical-namespaces) | https://github.com/kubernetes-sigs/hierarchical-namespaces/pull/333
- [x] [kubernetes/design-proposals-archive](https://github.com/kubernetes/design-proposals-archive) | [search result](https://cs.k8s.io/?q=k8s-testgrid.appspot.com&i=nope&files=&excludeFiles=&repos=kubernetes/design-proposals-archive) | (repository archived)

**How can the assignee reach out for help?**
You can have a look at this similar PR: https://github.com/kubernetes/sig-release/pull/2305
Or
Ask your questions in the comment.

NOTE: Please mention this issue in your PR so that it can be tracked and duplicate work can be minimised.

**Comment by Aayush987** [comment]
Hi @neolit123 , I have done the changes in the kubeadm repository. I have also opened the pr for the same.

**Comment by Ritikaa96** [comment]
I'll be working on the kuberenetes/community related changes as it doesn't seem anyone has started work on it.

**Comment by letmerecall** [comment]
> I'll be working on the kuberenetes/community related changes as it doesn't seem anyone has started work on it.

Thanks @Ritikaa96! Feel free to reference this issue in your PR :)

**Comment by mohitsharma-in** [comment]
I've created PR for k/release repo @letmerecall  feel free to review/update in this issue 
 https://github.com/kubernetes/release/pull/3211

**Comment by AdityaVardhanSingh** [comment]
Hey, can I make a PR for this issue?

**Comment by letmerecall** [comment]
> Hey, can I make a PR for this issue?

Sure @AdityaVardhanSingh, feel free to make a PR in any of the affect repositoriy.

**Comment by Ritikaa96** [comment]
This issue isnt closed yet , 
/remove closed

**Comment by Ritikaa96** [comment]
This Issue isnt closed yet
/reopen

**Comment by letmerecall** [comment]
Not closed yet.
/reopen

**Comment by Ritikaa96** [comment]
This issue isnt closed yet 
/reopen

**Comment by maclo2012** [comment]
Hello. I would like to work on this issue, may I?

**Comment by letmerecall** [comment]
> Hello. I would like to work on this issue, may I?

Thanks for the help @maclo2012, but I think we have all the tasks either completed or in review for this issue :)
