### ISSUE TITLE
Migration of etcd-io/etcd GitHub Actions to Prow

### ISSUE THREAD

**Issue by ArkaSaha30** [kubernetes/test-infra#32754]
**What should be cleaned up or changed**:
As a part of the migration, following GitHub Actions running as presubmits/postsubmits/periodics may need to be migrated to Prow: 

`main`:
- [ ] [contrib.yaml](https://github.com/etcd-io/etcd/blob/main/.github/workflows/contrib.yaml)
- [ ] [coverage.yaml](https://github.com/etcd-io/etcd/blob/main/.github/workflows/coverage.yaml)
- [ ] [fuzzing.yaml](https://github.com/etcd-io/etcd/blob/main/.github/workflows/fuzzing.yaml)
- [ ] [govuln.yaml](https://github.com/etcd-io/etcd/blob/main/.github/workflows/govuln.yaml)
- [ ] [grpcproxy.yaml](https://github.com/etcd-io/etcd/blob/main/.github/workflows/grpcproxy.yaml) 
- [ ] [measure-testgrid-flakiness.yaml](https://github.com/etcd-io/etcd/blob/main/.github/workflows/measure-testgrid-flakiness.yaml)
- [ ] [release.yaml](https://github.com/etcd-io/etcd/blob/main/.github/workflows/release.yaml)

`release-3.5`:
- [ ] [functional.yaml](https://github.com/etcd-io/etcd/blob/release-3.5/.github/workflows/functional.yaml)
- [ ] [govuln.yaml](https://github.com/etcd-io/etcd/blob/release-3.5/.github/workflows/govuln.yaml)
- [ ] [grpcproxy.yaml](https://github.com/etcd-io/etcd/blob/release-3.5/.github/workflows/grpcproxy.yaml)
- [ ] [release.yaml](https://github.com/etcd-io/etcd/blob/release-3.5/.github/workflows/release.yaml)
- [ ] [static-analysis.yaml](https://github.com/etcd-io/etcd/blob/release-3.5/.github/workflows/static-analysis.yaml)

`release-3.4`
- [ ] [govuln.yaml](https://github.com/etcd-io/etcd/blob/release-3.4/.github/workflows/govuln.yaml)
- [ ] [release.yaml](https://github.com/etcd-io/etcd/blob/release-3.4/.github/workflows/release.yaml)
- [ ] [static-analysis.yaml](https://github.com/etcd-io/etcd/blob/release-3.4/.github/workflows/static-analysis.yaml)

**Provide any links for context**:
Parent Issue ref: https://github.com/kubernetes/k8s.io/issues/6102

**Comment by ArkaSaha30** [comment]
This is an initial list of GitHub workflows I have identified for the migration, please review the list if anything needs to be added/removed.

/sig etcd

**Comment by ArkaSaha30** [comment]
/assign 

cc @jmhbnz @ahrtr @serathius

**Comment by ahrtr** [comment]
Also link to https://github.com/kubernetes/k8s.io/issues/6102

**Comment by ivanvc** [comment]
I wasn't aware of this task. Watching now.

**Comment by ivanvc** [comment]
/remove-lifecycle stale

@ArkaSaha30, the completion track is not up to date. But I don't have permission to edit your description. Should I create a new ticket to track the completion? So I can update it? Let me know.

**Comment by ivanvc** [comment]
Refer to https://github.com/kubernetes/test-infra/issues/32754#issuecomment-2942746295

**Comment by ivanvc** [comment]
We'll be removing release-3.5's test-smoke job. The [Makefile target](https://github.com/etcd-io/etcd/blob/2243367ddbf7aa1f2f7312234275ca8927defcfb/Makefile#L159) is the following:

```Makefile
test-smoke:
	$(info log-file: test-$(TEST_SUFFIX).log)
	PASSES="fmt bom dep build unit" ./test.sh 2<&1 | tee test-$(TEST_SUFFIX).log
	! grep "FAIL:" test-$(TEST_SUFFIX).log
```

All the passes it runs are duplicated:
1. `fmt`: It's replaced by verify
2. `bom`: It's part of verify
3. `dep`: It's part of verify
4. `build`: Covered already by build and by release tests
5. `unit`: We already have a unit test job

**Comment by ivanvc** [comment]
Refer to https://github.com/kubernetes/test-infra/issues/32754#issuecomment-3014660991

**Comment by ivanvc** [comment]
X-posting https://github.com/etcd-io/etcd/pull/20116#issuecomment-2950067337, as we're having issues running 3.4 e2e tests on the Prow infra.

> @joshjms, I can think of two solutions:
> 
> 1. We run the tests on the Prow infra using a different image, which will require a different job configuration for release-3.4 e2e jobs
> 2. We keep this job as a GitHub action/workflow
> 
> Given the timeline to give support to this version, I lean towards option 2.
> 
> That would mean:
> 1. Keep the `tests.yaml` file, simplify it, so it only runs e2e tests
> 2. Revert https://github.com/kubernetes/test-infra/pull/34916
> 
> @jmhbnz, thoughts?

Edit: We're backporting the e2e tests change to release-3.4.

**Comment by ivanvc** [comment]
And now, with the activity, my comment keeps getting hidden. So, copying https://github.com/kubernetes/test-infra/issues/32754#issuecomment-2942746295 to the bottom to keep it visible.

---

Because I don't have access to update the issue. I'll start my own completion matrix below:

`main`:

- [x] [contrib.yaml](https://github.com/etcd-io/etcd/blob/main/.github/workflows/contrib.yaml)
- [x] [coverage.yaml](https://github.com/etcd-io/etcd/blob/main/.github/workflows/coverage.yaml)
- [x] [fuzzing.yaml](https://github.com/etcd-io/etcd/blob/main/.github/workflows/fuzzing.yaml)
- [x] [govuln.yaml](https://github.com/etcd-io/etcd/blob/main/.github/workflows/govuln.yaml)
- [x] [grpcproxy.yaml](https://github.com/etcd-io/etcd/blob/main/.github/workflows/grpcproxy.yaml)
- [ ] [measure-testgrid-flakiness.yaml](https://github.com/etcd-io/etcd/blob/main/.github/workflows/measure-testgrid-flakiness.yaml) - Doesn't apply. Check with Siyuan if we still need this workflow.
- [x] [release.yaml](https://github.com/etcd-io/etcd/blob/main/.github/workflows/release.yaml)

`release-3.5`:

- [x] [e2e.yaml](https://github.com/etcd-io/etcd/blob/release-3.5/.github/workflows/e2e.yaml)
  - [x] #35053 
  - [x] https://github.com/etcd-io/etcd/pull/20315
- [x] [~functional.yaml~](https://github.com/etcd-io/etcd/blob/release-3.5/.github/workflows/functional.yaml): Just remove the workflow (refer to https://github.com/etcd-io/etcd/pull/20021#issuecomment-2918549192) - https://github.com/etcd-io/etcd/pull/20315
- [x] [govuln.yaml](https://github.com/etcd-io/etcd/blob/release-3.5/.github/workflows/govuln.yaml)
  - [x] #35050
  - [x] etcd-io/etcd#20172
  - [x] https://github.com/etcd-io/etcd/pull/20315
- [x] [grpcproxy.yaml](https://github.com/etcd-io/etcd/blob/release-3.5/.github/workflows/grpcproxy.yaml)
  - [x] etcd-io/etcd#20197
  - [x] #35044
  - [x] etcd-io/etcd#20236
- [x] [release.yaml](https://github.com/etcd-io/etcd/blob/release-3.5/.github/workflows/release.yaml)
  - [x] etcd-io/etcd#20168
  - [x] etcd-io/etcd#20293
  - [x] #35098
  - [x] https://github.com/etcd-io/etcd/pull/20315
- [x] [static-analysis.yaml](https://github.com/etcd-io/etcd/blob/release-3.5/.github/workflows/static-analysis.yaml)
  - [x] https://github.com/kubernetes/test-infra/pull/34782
  - [x] Implement missing verify targets: etcd-io/etcd#20046
  - [x] etcd-io/etcd#20099
- [x] [tests.yaml](https://github.com/etcd-io/etcd/blob/release-3.5/.github/workflows/tests.yaml)
  - [x] https://github.com/etcd-io/etcd/pull/20315
  - [x] etcd-io/etcd#20198 is blocking integration tests and the rest of the progress.
  - [x] ~amd64 smoke~: Delete this job (and the arm64 one). Refer to https://github.com/kubernetes/test-infra/issues/32754#issuecomment-2920762844
  - [x] amd64 integration, 1 2, and 4 CPUs
    - [x] #34983
    - [x] #34989
  - [x] arm64/amd64/i386 unit
    - [x] #35000
    - [x] #35011
  - [x] ~all-build (cross-compiling): Probably not needed, as covered by release tests.~

`release-3.4`:

- [x] [govuln.yaml](https://github.com/etcd-io/etcd/blob/release-3.4/.github/workflows/govuln.yaml)
  - [x] etcd-io/etcd#19810
  - [x] #34737
  - [x] etcd-io/etcd#19881
- [x] [release.yaml](https://github.com/etcd-io/etcd/blob/release-3.4/.github/workflows/release.yaml)
  - [x] etcd-io/etcd#19815
  - [x] #34740 
  - [x] etcd-io/etcd#19877
- [x] [static-analysis.yaml](https://github.com/etcd-io/etcd/blob/release-3.4/.github/workflows/static-analysis.yaml)
  - [x] etcd-io/etcd#19911
  - [x] https://github.com/etcd-io/etcd/pull/20011
- [x] [tests.yaml](https://github.com/etcd-io/etcd/blob/release-3.4/.github/workflows/tests.yaml)
  - [x] etcd-io/etcd#20116
  - [x] amd64 integration, 1 2, and 4 CPUs
    - [x] 4 CPUs: #34843
    - [x] 2, 1 CPUs: #34877
  - [x] ~amd64 functional~: Just remove the workflow (refer to https://github.com/etcd-io/etcd/pull/20021#issuecomment-2918549192)
    - [x] etcd-io/etcd#20021
    - [x] ~#34849~
  - [x] amd64 unit 4 CPUs, 386 unit 1 CPU - #34883
  - [x] amd64 grcpproxy
    - [x] etcd-io/etcd#20063
    - [x] #34891
  - [x] amd64 e2e
    - [x] etcd-io/etcd#20136 
    - [x] #34916 
    - [x] #34955
  - [x] ~all-build (cross-compiling): Probably not needed, as covered by release tests.~

**Comment by ivanvc** [comment]
With all tasks completed, we have successfully migrated the Prow repository to etcd. Thanks for all your work, @joshjms and @abdurrehman107 :)

/close
