### ISSUE TITLE
KEP-3041 - Tracking Work

### ISSUE THREAD

**Issue by kannon92** [kubernetes/test-infra#33823]
**What would you like to be added**:

As part of https://github.com/kubernetes/enhancements/tree/master/keps/sig-testing/3041-node-conformance-and-features, I would like to work on cleaning up our test-infra for sig-node.
**Why is this needed**:

Testing is hard enough and we have so many labels that are not necessary used. Let's try and move all special labels to  feature at the moment.

```[tasklist]
### Tasks
- [x] Kubernetes PR to remove NodeSpecialFeature and NodeAlphaFeature - https://github.com/kubernetes/kubernetes/pull/128923
- [x] Test-Infra PR to remove NodeSpecialFeature and NodeAlphaFeature - https://github.com/kubernetes/test-infra/pull/33828
- [x] Verify NodeSpecialFeature/NodeAlphaFeature PR did not break anything
- [x] Kubernetes PR to deprecate node features - https://github.com/kubernetes/kubernetes/pull/129166
- [ ] https://github.com/kubernetes/community/pull/8229
- [x] Verify deprecation of NodeFeature
- [x] Drop NodeFeature from test-infra - https://github.com/kubernetes/test-infra/pull/33931
- [x] Kubernetes PR to remove node features - https://github.com/kubernetes/kubernetes/pull/129168
```

**Comment by kannon92** [comment]
https://github.com/kubernetes/kubernetes/pull/128923 and https://github.com/kubernetes/test-infra/pull/33828 have merged. Tomorrow I will verify that the tests are running.

**Comment by kannon92** [comment]
https://github.com/kubernetes/test-infra/issues/33823#issuecomment-2549751155

We are good to go with the second part of this issue.

Once I am back from PTO, I'd like to land https://github.com/kubernetes/kubernetes/pull/129166 in January.

**Comment by kannon92** [comment]
Last time is https://github.com/kubernetes/kubernetes/pull/129168 and then we can close this as done once that merges.

**Comment by kannon92** [comment]
Looking at test grid, I don't see any impacts from this change anymore.

We can close this as complete.

/close
