### ISSUE TITLE
[Umbrella Issue] Enable Mungebot in Community Repo

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#3675]
Turn on the mungebot in the community repo.

- [x] identify which mungers we want turned on (size, SQ, blunderbuss, approvers, etc)
- [x] generate OWNERS files for community repo
- [x] create configmap for community
- [x] write MAKEFILE for easy mungebot deployment

**Comment by grodrigues3** [comment]
@kubernetes/sig-contributor-experience-feature-requests @spiffxp

**Comment by spiffxp** [comment]
/assign @cjwagner 

I think you're working on the last checkbox at least, per comments during latest sig-testing meeting about "standardizing behavior across all repos" I wasn't sure if you own the first two checkboxes

**Comment by fejta** [comment]
Pretty sure this is done?
