### ISSUE TITLE
Implement Bazel Remote Caching [Tracking Issue]

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#6808]
Bazel `0.10.0` is now in use in test-infra and kubernetes (release-1.10/master). This release contains some nice improvements to [the HTTP remote caching](https://docs.bazel.build/versions/master/remote-caching.html) system, we should leverage this instead of our existing "use persistent storage for the local cache".

Why?
- using a remote cache means the cache is *global* so all jobs can share it
- the remote cache is (mostly) content addressed and *designed* for sharing, the local cache is not so much
- we can't have a broken node with a bad cache to hunt down if we don't put the cache on the node

Why not?
- it's another thing to deploy and keep an eye on
- bugs / invalid caching can break builds
  - More specifically see https://github.com/bazelbuild/bazel/issues/4558
  - NOTE: we've found multiple work arounds for this and implemented one, see below

Action Items
- [x] configure bazel for remote caching and test this by building and testing test-infra, kubernetes, etc.
- [x] automate configuration (ref: https://github.com/kubernetes/test-infra/pull/6661, https://github.com/kubernetes/test-infra/pull/6673, https://github.com/kubernetes/test-infra/pull/6682, https://github.com/kubernetes/test-infra/pull/6685)
  - NOTE: we're working around the invalid caching issue by auto configuring jobs to point to a (per-repo, per-host-tools-versions (hashed)) cache, so they simply use a different cache
- [x] evaluate caching backends (some discussion here: https://github.com/kubernetes/test-infra/pull/6767)
  - GCS is nice and definitely something to consider, but having the cache in-cluster should be faster and we can control the cache size / costs / eviction better.
  - Hazelcast is a fancy distributed cache, but much more complex and comes with JVM baggage
  - nginx with webdav or apache httpd with webdav works, but in particular doesn't handle eviction, stats etc.
  - [bazel-remote](https://github.com/buchgr/bazel-remote) is great, but we want to host one server for multiple "caches" so we can split up repos etc. to be defensive about incorrect caching
  - [Our own minimal implementation](https://github.com/kubernetes/test-infra/tree/master/greenhouse): easy enough, [the protocol](https://docs.bazel.build/versions/master/remote-caching.html#http-caching-protocol) is *essentially* just HTTP PUT/GET of blobs
- Improve [our implementation](https://github.com/kubernetes/test-infra/tree/master/greenhouse)
   - [x] implement an eviction strategy (https://github.com/kubernetes/test-infra/pull/6812)
   - [x] document (https://github.com/kubernetes/test-infra/pull/6879)
   - [x] rename from `nursery` to `greenhouse` to be less confusing :-) (https://github.com/kubernetes/test-infra/pull/6879)
   - [x] add metrics
- [x] set up monitoring / dashboard
- roll out to "real" jobs / integrate with our images [WIP (test-infra)]
  - [x] integrate into our images (https://github.com/kubernetes/test-infra/pull/6859)
  - [x] enable for test-infra (https://github.com/kubernetes/test-infra/pull/6879)
  - [x] enable for everyone else who wants it (talked to cluster-registry, they're now using it) [WIP]
  - [x] enable for kubernetes (rolled out to ci bazel build / test, presubmit test) [WIP]
  

/area bazel
/area jobs
/assign

**Comment by BenTheElder** [comment]
Some more notes:
- The invalid cache sharing work around seems to work well with the canary jobs at least
- Experimental Jobs using the cache can be *much* faster: 
  - `pull-kubernetes-bazel-test` takes 25-30m currently, once the cache is hot `pull-kubernetes-bazel-test-canary` takes ~5min typically. There is a lot of variation for both though mostly due to the load on the node the job runs on
  - `pull-test-infra-bazel` takes 8-10m currently, `pull-test-infra-bazel-canary` takes ~3 min (about two minutes of which is spent installing python deps and running pylint...)
  - `pull-kubernetes-bazel-build-canary` is not caching well currently, we probably need to mark things like hyperkube and the tarballs as [`no-cache`](https://docs.bazel.build/versions/master/remote-caching.html#exclude-specific-targets-from-using-the-remote-cache)

**Comment by BenTheElder** [comment]
FYI @perotinus we can probably look at using this with the cluster-registry soon, test-infra is using it now 😄

**Comment by BenTheElder** [comment]
Tested eviction a bit more with: https://github.com/BenTheElder/test-infra/blob/20d7d58ac34d59e241eddfb107e3b735398cd8d7/experiment/fill_cache.sh
Will PR some logging changes but so far WAI

**Comment by BenTheElder** [comment]
Testing [a new test-infra PR](https://github.com/kubernetes/test-infra/pull/6932) appears to have 3468 action cache hits, 7 action cache misses, and 1920 CAS hits (!)

**Comment by BenTheElder** [comment]
I've now turned this on for the kubernetes CI [bazel-build](https://k8s-testgrid.appspot.com/sig-release-master-blocking#bazel-build&graph-metrics=test-duration-minutes&width=5) and [bazel-test](https://k8s-testgrid.appspot.com/sig-release-master-blocking#bazel-test&graph-metrics=test-duration-minutes&width=5) jobs with great results*
<img width="1790" alt="screen shot 2018-02-24 at 11 30 28 am" src="https://user-images.githubusercontent.com/917931/36634315-864d8ae2-1957-11e8-9dea-2dd6c7a2d932.png">
<img width="1790" alt="screen shot 2018-02-24 at 11 42 01 am" src="https://user-images.githubusercontent.com/917931/36634324-c1b6876e-1957-11e8-8734-85437f4153fe.png">
\* Note: the build job only runs in post-submit, and once every 6 hours, currently. Once this job is properly continuous the results for it will be more obvious.

We also have [a monitoring dashboard](http://velodrome.k8s.io/dashboard/db/cache-monitoring?orgId=1&from=now-24h&to=now) now:
<img width="1790" alt="screen shot 2018-02-24 at 11 31 27 am" src="https://user-images.githubusercontent.com/917931/36634338-eda555bc-1957-11e8-8f75-ffd42602eee3.png">

**Comment by BenTheElder** [comment]
https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-bazel-test&graph-metrics=test-duration-minutes

As expected instead of ~25+ minutes we're seeing ~5-6 minutes for `pull-kubernetes-bazel-test` after switching this on today.

**Comment by buchgr** [comment]
Absolutely *amazing* work @BenTheElder. Congratulations!

**Comment by BenTheElder** [comment]
Thanks Jakob :-)

**Comment by BenTheElder** [comment]
[kops](https://github.com/kubernetes/kops) is now using the remote cache, 8+ minutes to test -> ~2 minutes

https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/pull/kops/4565/pull-kops-bazel-test/

**Comment by BenTheElder** [comment]
I think once https://github.com/kubernetes/test-infra/pull/7205 is in we can close this, I've significantly upped the cache storage and we're flipping it on for pretty much all other presubmits that should leverage caching.

**Comment by BenTheElder** [comment]
/close
We've rolled this out to many more jobs, `pull-kubernetes-bazel-build` in particular is now trending towards 5-8 minutes instead of 13+
![image](https://user-images.githubusercontent.com/917931/37305532-f7bcb3e6-25f1-11e8-9b91-e0100ef43c6a.png)

**Comment by buchgr** [comment]
woohooo!!! 🍾 🎆 🎉 

cc @ulfjack
