### ISSUE TITLE
Presubmits Should be much Faster [Tracking Issue]

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#6865]
I'm working on a number of things in this area, so I'm just going to consolidate them here with the unified goal of speeding up our tests.

- [x] Leverage [Bazel remote caching](https://docs.bazel.build/versions/master/remote-caching.html) for global shared build / unit test cache (WIP, see more in depth issue here: https://github.com/kubernetes/test-infra/issues/6808)
- [ ] Leverage Bazel's build / test parallelism by throwing more cores at our jobs
  - [ ] Requires improving resource allocation / probably using guaranteed QoS
  - [x] Requires removing local SSD caching hacks to unblock node level scheduling parallelism so we can combine our quota into larger nodes with job bin-packing instead of ~one presubmit to a node currently [WIP] (https://github.com/kubernetes/test-infra/pull/7202... and many others)
    - [x] Eliminate git caching via local SSD by leveraging initContainer + emptyDir shared volume
    - [x] Eliminate bazel local caching by switching to shared remote caching
    - [x] Eliminate docker in docker using a single cache dir / port, switch more of these to emptyDir [WIP]
    - [x] When the above are fixed remove hostPort 9999 from these jobs (our "one to a node" lock)
    - [x] start reshaping Prow's build / test cluster towards larger VMs
- [x] Leverage `typecheck` from @rmmh as much as possible instead of an actual cross build to verify that there are not platform / arch specific breakages. (WIP)
- [ ] Don't run "Teardown" phase for presubmit jobs, let Boskos do cleanup instead (~10 minutes / job).
- X - EDIT: the following is rather unlikely :/
Use shallow checkouts for repos that do not need git tags, investigate how badly kubernetes actually needs to use git tags (probably a lost cause for many repos, but shallow clones are much simpler and faster than fetching the whole git history + tags...)

It's of course also helpful if people don't write slow, brittle presubmits, but this should get us a *lot* of lost ground back for most of our tests doing highly parallel and cacheable tasks.

/kind feature
/area jobs

**Comment by BenTheElder** [comment]
@cjwagner @stevekuznetsov I'm going to set up a git pre-cloned container + shared volume today on a test job, in the future we should customize the git checkout container for the kubernetes prow deployment to contain this data and periodically update it.

**Comment by BenTheElder** [comment]
cc @spiffxp, this covers a lot of the work I want to get in ~ this quarter for test-infra other than testgrid + confromance results and helping with bootstrap + prow integration. 

I think we [can already slash `pull-kubernetes-bazel-test` to ~5-8 minutes](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-bazel-test-canary/) instead of [25-30](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-bazel-test/) (note: times are variable due to node pressure / burstable QoS and purging the cache) and I'm looking for similar gains elsewhere.

**Comment by BenTheElder** [comment]
`pull-test-infra-bazel` and `pull-kubernetes-bazel-test` should be much faster now (due to remote caching), I'm also starting to soak @rmmh's awesome typechecker https://github.com/kubernetes/test-infra/pull/7059 which should let us slash the "fail fast when code won't build" time.

**Comment by BenTheElder** [comment]
- we've rolled out the bazel remote caching to more places
- typecheck will be blocking soon instead of cross for ~4-5min instead of ~1 hour
- only 92 hits for hostport left in prow/config.yaml, I'm working to eliminate more of these so we can switch over to less-but-larger machines in our cluster with (larger) guaranteed resources for build jobs instead of burstable QoS over many machines

**Comment by BenTheElder** [comment]
I've done as much as I'll have time for on this for now, we can follow up on this more in the future perhaps
/close
