### ISSUE TITLE
Automate Protection of Branches and Required Status Contexts

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#8650]
We need a tool that will allow us to configure branch protection and required status contexts using declarative configuration.

 - [x]  Add branch-protection program #6077 
 - [x]  Refactor Requirements to use a BranchProtectionRequest #7937 
 - [x]  Refactor UpdateBranchProtection to update all options #7911 
 - [x]  Refactor TestProtect into an integration test #7891 
 - [x]  Refactor branchprotection config. #7674 
 - [x]  Enable pure go for branchprotector image #7662 
 - [x]  Add some user docs for branchprotector #6701 
 - [x]  Create branchprotector cronjob for prod, job for dev #6205 
 - [x]  Declare current protection config for all kubernetes repos #8091 
 - [x]  Protect all kubernetes/* repos by default #8067 
 - [x]  Update README.md to include all protection fields #8049 
 - [x]  Use non-deprecated branch protection policy fields #8019 
 - [x]  Do not unprotect already unprotected branches #8014 
 - [x]  Optionally allow children to disable parent policies #8001 
 - [x]  Expand Policy to include all protection options #7984 

/area prow
/kind feature
/assign @fejta 
/cc @cjwagner @BenTheElder

**Comment by stevekuznetsov** [comment]
I think this work is finished, all repos are protected by default.
/close
