### ISSUE TITLE
DinD tracking issue

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#8812]
We use Docker in Docker pretty successfully for various things in test-infra but it needs some work.

- [x] 1. We need an image with DinD and podutils support to supersede `images/bootstrap`, see also https://github.com/kubernetes/test-infra/issues/8779, https://github.com/kubernetes/test-infra/issues/8780
  - we can probably just refactor the `ENTRYPOINT` runner a bit to allow it also being used by certain jobs, without the bootstrap bit and with the real test command instead.

- [x] 2. We should make our existing support a pod-preset so that it's easier to use. At this point it's used widely enough that we should remove all of the copy paste for env / volumes. This will make it easier to refactor how the support works.

- [x] 3. We have a couple of areas where we've worked on running "local clusters" within the test as a cheaper / more hermetic way to test, but none of these is quite fully baked, and they have a few issues integrating currently (mostly improper cleanup / making sure they work with the DinD they are already on from 1) when doing DinD on <prow image> on <prow node> [dindind etc...], but some others as well).. We should improve these. To that end I am in particular taking another look at `dind/`.

/area jobs
/assign

**Comment by BenTheElder** [comment]
#3 moved to sigs.k8s.io/kind. will migrate tracking of remaining work to there generally.
