### ISSUE TITLE
Modernise Deck JavaScript

### ISSUE THREAD

**Issue by Katharine** [kubernetes/test-infra#9478]
Deck's front-end could use some cleanup! Let's work toward that.

- [x] Move the frontend to templates instead of repetition and client-side overwriting (#9465)
- [x] Move Spyglass templates from Go files to HTML files (#9488)
- [ ] Remove the pervasive JSON-P in favour of fetch/xhr
- [x] Introduce a JavaScript build process (#9543)
- [x] Move to TypeScript (#9622, #9623, #9624, #9625, #9626)
- [ ] modularise the JavaScript, and use modern features as appropriate.
- [ ] Add unit tests

/area prow/deck
/kind cleanup

**Comment by BenTheElder** [comment]
+1 for typescript. Thanks for working on this 😀

**Comment by paulangton** [comment]
Another +1 for Typescript!

**Comment by qhuynh96** [comment]
`style.css` contains all the styling for every page in deck which will go huge as we are adding more features to deck. DYT we should separate/ modularize the styling sheet? @Katharine @BenTheElder

**Comment by BenTheElder** [comment]
I was just discussing this earlier today @qhuynh96, we should definitely do that :-)
